### PR TITLE
feat! switch to sync api

### PR DESCRIPTION
**Pull request by Gozala**
I end up building a new importer that uses sync API for building DAGs and this is a fork which makes hamt-sharding sync by requiring `SyncMultihashHasher` introduced by https://github.com/multiformats/js-multiformats/pull/160.

It also makes use of (version locked) sync murmur hasher introduced by https://github.com/multiformats/js-murmur3/pull/17

I do not know if landing this changes make sense at all, it may make more sense to release this as  separate library or maybe sync API can be provided along the side of current async API. Mostly this PR is here to start this conversation. Furthermore I do want to revamp hash-sharding library to simplify it make bit less stateful, I have WIP branch for this, but I have decided to pause that to finish up the new importer first.

### CODE REVIEW

**Comment by Gozala** [comment]
P.S. Can I get access to this repo, I had to fork it into my namespace to submit a PR

**Comment by BigLep** [comment]
@Gozala : per 2022-01-28 triage, a few things:
1. You now have access to this repo.
2. In terms of code reviewing this, we'll leave that to you and Nitro whether this is worth doing.  If it is worth doing, can you have Alen code review please?  As I understand, it sounds like Nitro was able to get unblocked via other means.

**Comment by lidel** [comment]
@Gozala any chance you will have time to finish this?

**Comment by lidel** [comment]
Feel free reopen when you have time to finish / find this still relevant.

**Pull request closed without merging**
